version: '3.8'

services:
  # Backend service
  backend:
    build: ./backend
    container_name: resume-classification-backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/uploads:/app/uploads
    environment:
      - FLASK_ENV=production
      - FLASK_APP=app.py
    restart: unless-stopped

  # Frontend service
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: resume-classification-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
